Manually uploaded all files from local repo
I'm not having any success debugging, rewriting my git history, or removing the entire .git file from the local repo; when I recreate it the large files just show up again in the commit history.

see also: https://stackoverflow.com/questions/2100907/how-to-remove-delete-a-large-file-from-commit-history-in-git-repository

Here's what I tried in the Terminal for reference:
(base) kathrynhurchla@Kathryns-MacBook-Pro threatened-species % git init
Reinitialized existing Git repository in /Users/kathrynhurchla/Documents/GitHub/threatened-species/.git/
(base) kathrynhurchla@Kathryns-MacBook-Pro threatened-species % git status
On branch main
Last commands done (3 commands done):
   squash ff2a857 published to remote repo
   pick 4445cf1 Initial commit
  (see more in file .git/rebase-merge/done)
Next command to do (1 remaining command):
   squash ff2a857 published to remote repo
  (use "git rebase --edit-todo" to view and edit)
You are currently editing a commit while rebasing branch 'main' on '8fc0972'.
  (use "git commit --amend" to amend the current commit)
  (use "git rebase --continue" once you are satisfied with your changes)

Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   .DS_Store
	modified:   README.md
	deleted:    output/threatened-species-sub-saharah-africa-west-indian-ocean.ai
	deleted:    output/threatened-species-sub-saharan-africa-west-indian-ocean.png

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	img/
	output/.DS_Store
	output/KathrynHurchla_ThreatenedSpecies-1_2021-07-20.pdf

no changes added to commit (use "git add" and/or "git commit -a")
(base) kathrynhurchla@Kathryns-MacBook-Pro threatened-species % git commit -a
[main ddfff64] reinitiated commit cleanly without large data files after removing git file
 4 files changed, 6 insertions(+), 1521 deletions(-)
 delete mode 100644 output/threatened-species-sub-saharah-africa-west-indian-ocean.ai
 delete mode 100644 output/threatened-species-sub-saharan-africa-west-indian-ocean.png
(base) kathrynhurchla@Kathryns-MacBook-Pro threatened-species % git remote add origin https://github.com/user/repo.git
error: remote origin already exists.
(base) kathrynhurchla@Kathryns-MacBook-Pro threatened-species % git remote add origin https://github.com/khurchla/threatened-species.git
error: remote origin already exists.
(base) kathrynhurchla@Kathryns-MacBook-Pro threatened-species % git push -u origin master
error: src refspec master does not match any
error: failed to push some refs to 'https://github.com/khurchla/threatened-species.git'
(base) kathrynhurchla@Kathryns-MacBook-Pro threatened-species % git push --force
fatal: The current branch main has no upstream branch.
To push the current branch and set the remote as upstream, use

    git push --set-upstream origin main

(base) kathrynhurchla@Kathryns-MacBook-Pro threatened-species % git push --set-upstream origin main
Username for 'https://github.com': khurchla
Password for 'https://khurchla@github.com': 
Enumerating objects: 46, done.
Counting objects: 100% (46/46), done.
Delta compression using up to 16 threads
Compressing objects: 100% (46/46), done.
Writing objects: 100% (46/46), 7.75 MiB | 5.44 MiB/s, done.
Total 46 (delta 19), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (19/19), done.
remote: error: Trace: a4fa694036a29cea1c189add16338ed282a5aadfd509000497343744b0fc9af2
remote: error: See http://git.io/iEPt8g for more information.
remote: error: File data/FW_GROUP_points.csv is 105.55 MB; this exceeds GitHub's file size limit of 100.00 MB
remote: error: GH001: Large files detected. You may want to try Git Large File Storage - https://git-lfs.github.com.
To https://github.com/khurchla/threatened-species.git
 ! [remote rejected] main -> main (pre-receive hook declined)
error: failed to push some refs to 'https://github.com/khurchla/threatened-species.git'